name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install arm target
      run: rustup target add thumbv6m-none-eabi
    - name: macro test
      run: cd macros && cargo test --no-run && cd -
    - name: build all examples
      run: cargo build --examples --release
